apiVersion: v1
kind: Service
metadata:
  name: file-server-svc
spec:
  ports:
    - name: file-server-svc
      port: 8080
      targetPort: 8080
      nodePort: 30800
  selector:
      stacker: backend
  type: NodePort