apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-server
  template:
    metadata:
      name: file-server-replicaset
      labels:
        app: file-server
    spec:
      containers:
        - name: file-server-pod
          image: #VERSION_STRING#
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: model-storage
              mountPath: /app/files/model
            - name: dataset-storage
              mountPath: /app/files/dataset
            - name: file-server-config
              mountPath: /app/config
            - name: tz-seoul
              mountPath: /etc/localtime
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: file-server-model-pvc
        - name: dataset-storage
          persistentVolumeClaim:
            claimName: file-server-dataset-pvc
        - name: file-server-config
          configMap:
              name: file-server-config 
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
