apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-server-pv
  labels:
    app: file-server
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s-pv/file-server"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-server-pvc
  accessModes:
    - ReadWriteOnce
  resource:
    requests:
      storage: 20Gi