apiVersion: apps/v1
kind: Deployment
metadata:
  name: sketch-brain-file-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sketch-brain-file-server
  template:
    metadata:
      name: sketch-brain-file-server-replicaset
      labels:
        app: sketch-brain-file-server
    spec:
      containers:
        - name: sketch-brain-file-server-pod
          image: hhlee7175/sketchbrain-file-server:v1.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: model-storage
              mountPath: /app/files/model
            - name: dataset-storage
              mountPath: /app/files/dataset
            - name: sketch-brain-file-server-config
              mountPath: /app/config
            - name: tz-seoul
              mountPath: /etc/localtime
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: sketch-brain-file-server-model-pvc
        - name: dataset-storage
          persistentVolumeClaim:
            claimName: sketch-brain-file-server-dataset-pvc
        - name: sketch-brain-file-server-config
          configMap:
            name: sketch-brain-file-server-config
        - name: tz-seoul
          hostPath:
            path: /usr/share/zoneinfo/Asia/Seoul
